name: sfx-test-2025-2025-6h-v1

description: test dataset for sfx

attribution: metno/surfex

licence: CC-BY-4.0

dates:
  start: '2025-12-15T00:00:00'
  end: '2025-12-15T00:00:00'
  frequency: 1h

input:
  netcdf:
    path: "forcings_with_topo_descriptors.nc"

statistics:
  allow_nans: true
