name: sfx-test-2025-2025-6h-v1

description: test dataset for sfx

attribution: metno/surfex

licence: CC-BY-4.0

dates:
  start: '2020-01-01T00:00:00'
  end: '2027-01-01T00:00:00'
  frequency: 8760h

build:
  group_by: 4

output:
  chunking: {dates: 1}


input:
  repeated-dates:
    mode: constant
    source:
      netcdf:
        path: "forcings_with_topo_descriptors.nc"

statistics:
  allow_nans: false
